### ISSUE TITLE
Issue with v2.0.0 (data  bag related)

### ISSUE THREAD

**Issue by rmoriz** [chef-cookbooks/ssh_known_hosts#37]
With v2.0.0 we're getting the following error when we run our ChefSpec specs for a cookbook that uses ssh_known_hosts:

```
TypeError
---------
no implicit conversion of Array into String
```

```
Relevant File Content:
----------------------
/var/folders/48/v3jpvqg155d2qfktth99_8t40000gp/T/d20141205-96021-7o92di/cookbooks/ssh_known_hosts/recipes/default.rb:

 55:                              }
 56:      end
 57:    end
 58:  end
 59:  
 60:  # Add the data from the data_bag to the list of nodes.
 61:  # We need to rescue in case the data_bag doesn't exist.
 62>> if Chef::DataBag.list.key?('ssh_known_hosts')
 63:    begin
 64:      hosts += data_bag('ssh_known_hosts').collect do |item|
 65:        entry = data_bag_item('ssh_known_hosts', item)
 66:        {
 67:          'fqdn' => entry['fqdn'] || entry['ipaddress'] || entry['hostname'],
 68:          'key'  => entry['rsa'] || entry['dsa']
 69:        }
 70:      end
 71:    rescue
```

our usage in a recipe:

```
include_recipe 'ssh_known_hosts'
ssh_known_hosts_entry 'github.com'
```

no data bags.

**Comment by stevemartin** [comment]
+1  (Chef Solo + Vagrant + Ubuntu 14.04 - not ChefSpec )

**Comment by tas50** [comment]
You'll need to use the ServerRunner to avoid getting data bag errors or you'll need to mock out the data bag in solo.

**Comment by rmoriz** [comment]
It's IMHO a kind of a bad default to rely on ServerRunner and not catch the error in the recipe caused by false assumptions.

**Comment by mikelococo** [comment]
I'm also somewhat stuck by this error.

1. I'm also -1 on the ServerRunner recommendation. It's less well documented, less widely used, and seems to have a fairly regular stream of bugs associated with api-breaking changes in chef-zero occurring in minor releases.
2. Stubbing the data-bags for chef-solo sounds like a reasonable workaround, but dropping "stub_data_bag('ssh_known_hosts').and_return([])" into a before block doesn't seem to be sufficient to complete a run.
3. Neither of these techniques is demoed in the the chefspec for this cookbook. I'm not able to identify what it does differently from my own spec.

It's also worth bearing in mind that in addition to the data-bag based work this cookbook does, it's also a library cookbook that provides an LWRP for managing host-keys. That's the only part of it that I wish to use and for my use, it would be best if the default recipe was empty. Having to stub out data bag calls in order to get access to an LWRP feels out of proportion.
